### ISSUE TITLE
Registration error

### ISSUE THREAD

**Issue by anselal** [rtzll/flask-todolist#4]
Hi there,

I run the up with docker compose and when I submitted my registration I got the following error:

```sh
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user [SQL: 'SELECT user.username AS user_username, user.email AS user_email, user.id AS user_id, user.password_hash AS user_password_hash, user.member_since AS user_member_since, user.last_seen AS user_last_seen, user.is_admin AS user_is_admin \nFROM user \nWHERE user.email = ?\n LIMIT ? OFFSET ?'] [parameters: ('anselal@auth.gr', 1, 0)] (Background on this error at: http://sqlalche.me/e/e3q8)
```

It seems that the table does not exist. Aren't the tables created automatically at runtime ?

**Comment by rtzll** [comment]
Yes, it should be created by running `flask db upgrade` which is in the `docker-compose.yml`.
But I could reproduce the problem... :confused:

To workaround this you can log into the container while it's running: `docker exec -it todolist sh` and then do `flask db upgrade`. Now the tables are created.

Not sure when I'll find time to understand/fix this. I hope this is helpful for now.

**Comment by anselal** [comment]
Yeah, that fixed the issue. Thanks for the quick reply.

I am not very familiar yet with how docker-compose actually works. I work only with docker for now.

I will take a loot at it and try to figure out why the command was not running

**Comment by anselal** [comment]
Cool !!!
